export const FORM_CONSTANTS = {
  ADD_TITLE: "New Member",
  EDIT_TITLE: "Edit Member",
  ADD_BTN_TXT: "Add Member",
  EDIT_BTN_TXT: "Save Changes",

  SECTION_TITLES: {
    MEMBER_DETAILS: "Member Details",
    FEES_AND_DUES: "Fees & Dues",
    ACTIVITY_DETAILS: "Activity Details",
  },

  LABELS: {
    PROFILE_PICTURE: "Profile Picture",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    MEMBER_STATUS: "Membership Status",
    JOIN_DATE: "Joined Date",
    EMAIL_ADDRESS: "Email Address",
    PHONE_NUMBER: "Phone Number",
    LEAD_SOURCE: "Lead Source",
    MEMBERSHIP_CATEGORY: "Membership Category",
    MONTHLY_DUES: "Monthly Dues",
    INITIATION_FEE: "Initiation Fee",
    ACTIVITY_DATE_TIME: "Activity Date & Time",
    ACTIVITY_TYPE: "Activity Type",
    ACTIVITY_DESCRIPTION: "Activity Description",
    BIRTH_DATE: "Birth Date",
    MEMBERSHIP_TYPE: "Membership Type",
    RESIGNATION_DATE: "Resignation Date",
    RESIDENTIAL_ADDRESS: "Residential Address",
  },

  PLACEHOLDERS: {
    FIRST_NAME: "Enter first name",
    LAST_NAME: "Enter last name",
    MEMBER_STATUS: "Select members status",
    JOIN_DATE: "Select Joined Date date",
    EMAIL_ADDRESS: "Enter email address",
    PHONE_NUMBER: "Phone number",
    LEAD_SOURCE: "Select lead source",
    MEMBERSHIP_CATEGORY: "Select membership category",
    MONTHLY_DUES: "Enter monthly dues",
    INITIATION_FEE: "Enter initiation fee",
    ACTIVITY_DATE_TIME: "Enter activity date & time",
    ACTIVITY_TYPE: "Select activity type",
    ACTIVITY_DESCRIPTION: "Add activity description",
    BIRTH_DATE: "Select Birth Date",
    MEMBERSHIP_TYPE: "Select Membership Type",
    RESIGNATION_DATE: "Selectn Resignation Date",
    RESIDENTIAL_ADDRESS: "Enter Residential Address",
  },

  FIELD_NAMES: {
    PROFILE_PICTURE: "attachmentId",
    FIRST_NAME: "firstName",
    LAST_NAME: "lastName",
    MEMBER_STATUS: "membershipStatusId",
    JOIN_DATE: "joinedDate",
    EMAIL_ADDRESS: "email",
    PHONE_NUMBER: "contactNumber",
    PHONE_CODE: "phoneCode",
    BIRTH_DATE: "birthDate",
    LEAD_SOURCE: "leadSourceId",
    MEMBERSHIP_CATEGORY: "membershipCategoryId",
    MONTHLY_DUES: "monthlyDues",
    INITIATION_FEE: "initiationFee",
    MEMBERSHIP_TYPE: "membershipCategoryId",
    RESIGNATION_DATE: "resignationDate",
    RESIDENTIAL_ADDRESS: "residentialAddress",
    ACTIVITY_DATE_TIME: "activityDetails.createdAt",
    ACTIVITY_TYPE: "activityDetails.activityTypeId",
    ACTIVITY_DESCRIPTION: "activityDetails.description",
  },
};

export const memberHeaders = ["Members", "Joined Date", "Member Status"];
