export enum Buttons {
  LOGIN = "Login",
  CONFIRM_EMAIL = "Confirm email",
  BULK_MAIL = "Bulk Mail",
  ADD_PROSPECT = "Add Prospect",
  BACK_TO_LOGIN = "Back to Login",
  RESET_PASSWORD = "Reset Password",
  CANCEL = "Cancel",
  OK = "Ok",
  SAVE_CHANGES = "Save Changes",
  DELETE_PERMANENTLY = "Delete Permanently",
  BACK = "Back",
  YES_CONVERT = "Yes, Convert",
  APPLY_FILTERS = "Apply Filters",
  CLEAR_FILTERS = "Clear Filters",
  SELECT_ALL = "Select all",
  UNSELECT_ALL = "Unselect all",
  CLEAR = "Clear",
  NEXT = "Next",
  NEW_EMAIL = "New Email",
  ADD_STAFF = "Add Staff",
  ADD_MEMBER = "Add Member",
  SEND_EMAIL = "Send Email",
  UPLOAD_FILES = "Upload file(s)",
  ADD_TEMPLATE = "Add Template",
  ADD_CLUB = "Add Club",
  CLEAR_SELECTION = "Clear Selection",
  EDIT_PROFILE = "Edit Profile",
  CHANGE_PASSWORD = "Change Password",
  ADD_SLOTS = "Add Slot(s)",
  UPDATE_SLOTS = "Update Slot(s)",
  DOWNLOAD_TEMPLATE = "Download Template",
  CANCEL_UPLOAD = "Cancel Upload",
  CHANGE = "Change",
  IMPORT = "Import",
  YES_PROCEED = "Yes, Proceed",
  ADD_FILE = "Add File",
  ADD_CHART = "Add Chart",
  ADD_NAME = "Add Name",
  YES_UNLOCK = "Yes, Unlock",
}

export enum HtmlButtonType {
  SUBMIT = "submit",
  RESET = "reset",
  BUTTON = "button",
}

export enum AntdButtonType {
  PRIMARY = "primary",
  DASHED = "dashed",
  DEFAULT = "default",
  TEXT = "text",
  LINK = "link",
}

export enum ButtonSizes {
  SMALL = "small",
  MEDIUM = "medium",
  LARGE = "large",
}

export enum ButtonTypes {
  PRIMARY = "primary",
  DASHED = "dashed",
  DEFAULT = "default",
  TEXT = "text",
  LINK = "link",
  SECONDARY = "secondary",
  TERTIARY = "tertiary",
  SECONDARY_TWO = "secondaryTwo",
  TERTIARY_TWO = "tertiaryTwo",
  PRIMARY_TWO = "primaryTwo",
  TRANSPARENT = "transparent",
}
