export enum DateFormats {
  DD_MMM__YYYY = "DD MMM, YYYY",
  HH_MM_A__DD_MMM_YYYY = "hh:mm A, MMM DD, YYYY",
  DD_MMM_YYYY = "DD MMM YYYY",
  YYYY_MM_DD = "YYYY-MM-DD",
  HH_MM_A = "hh:mm A",
  DDD_MMM_DO = "ddd, MMM Do",
  HH_MM = "HH:mm",
  YYYY_MM = "YYYY-MM",
  DDD_MMM_DO_YYYY = "ddd, MMM Do YYYY",
  DD_MMM_YY = "DD MMM 'YY",
  MMMM_YYYY = "MMMM, YYYY",
  YYYY_MM_DD_T_HH_MM_SS = "YYYY-MM-DDTHH:mm:ss",
  MMM_DD__YYYY = "MMM DD, YYYY",
}
