export const ADD_PROSPECT_CONSTANTS = {
  MODAL_TITLE: "New Prospect",
  MODAL_WIDTH: 664,

  SECTION_TITLES: {
    LEAD_DETAILS: "Lead Details",
    FEES_AND_DUES: "Fees & Dues",
    ACTIVITY_DETAILS: "Activity Details",
  },

  LABELS: {
    PROFILE_PICTURE: "Profile Picture",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    LEAD_STATUS: "Lead Status",
    FOLLOW_UP_DATE: "Follow-up Date",
    EMAIL_ADDRESS: "Email Address",
    PHONE_NUMBER: "Phone Number",
    INQUIRY_DATE: "Inquiry Date",
    LEAD_SOURCE: "Lead Source",
    MEMBERSHIP_CATEGORY: "Membership Category",
    MONTHLY_DUES: "Monthly Dues",
    INITIATION_FEE: "Initiation Fee",
    ACTIVITY_DATE_TIME: "Activity Date & Time",
    ACTIVITY_TYPE: "Activity Type",
    ACTIVITY_DESCRIPTION: "Activity Description",
  },

  PLACEHOLDERS: {
    FIRST_NAME: "Enter first name",
    LAST_NAME: "Enter last name",
    LEAD_STATUS: "Select lead status",
    FOLLOW_UP_DATE: "Select follow-up date",
    EMAIL_ADDRESS: "Enter email address",
    PHONE_NUMBER: "Phone number",
    INQUIRY_DATE: "Select Date",
    LEAD_SOURCE: "Select lead source",
    MEMBERSHIP_CATEGORY: "Select membership category",
    MONTHLY_DUES: "Enter monthly dues",
    INITIATION_FEE: "Enter initiation fee",
    ACTIVITY_DATE_TIME: "Enter activity date & time",
    ACTIVITY_TYPE: "Select activity type",
    ACTIVITY_DESCRIPTION: "Add activity description",
  },

  FIELD_NAMES: {
    PROFILE_PICTURE: "profilePicture",
    FIRST_NAME: "firstName",
    LAST_NAME: "lastName",
    LEAD_STATUS: "leadStatus",
    FOLLOW_UP_DATE: "followUpDate",
    EMAIL_ADDRESS: "emailAddress",
    PHONE_NUMBER: "phone",
    PHONE_CODE: "phoneCode",
    INQUIRY_DATE: "inquiryDate",
    LEAD_SOURCE: "leadSource",
    MEMBERSHIP_CATEGORY: "membershipCategory",
    MONTHLY_DUES: "monthlyDues",
    INITIATION_FEE: "initiationFee",
    ACTIVITY_DATE_TIME: "activityDateTime",
    ACTIVITY_TYPE: "activityType",
    ACTIVITY_DESCRIPTION: "activityDescription",
  },
};
