export const phoneNumberData = {
  data: {
    mobileCodes: [
      {
        country: "Afghanistan",
        isoCode: "AF",
        phoneCode: "+93",
        flag: "🇦🇫",
      },
      {
        country: "Aland Islands",
        isoCode: "AX",
        phoneCode: "++358-18",
        flag: "🇦🇽",
      },
      {
        country: "Albania",
        isoCode: "AL",
        phoneCode: "+355",
        flag: "🇦🇱",
      },
      {
        country: "Algeria",
        isoCode: "DZ",
        phoneCode: "+213",
        flag: "🇩🇿",
      },
      {
        country: "American Samoa",
        isoCode: "AS",
        phoneCode: "++1-684",
        flag: "🇦🇸",
      },
      {
        country: "Andorra",
        isoCode: "AD",
        phoneCode: "+376",
        flag: "🇦🇩",
      },
      {
        country: "Angola",
        isoCode: "AO",
        phoneCode: "+244",
        flag: "🇦🇴",
      },
      {
        country: "Anguilla",
        isoCode: "AI",
        phoneCode: "++1-264",
        flag: "🇦🇮",
      },
      {
        country: "Antarctica",
        isoCode: "AQ",
        phoneCode: "+672",
        flag: "🇦🇶",
      },
      {
        country: "Antigua And Barbuda",
        isoCode: "AG",
        phoneCode: "++1-268",
        flag: "🇦🇬",
      },
      {
        country: "Argentina",
        isoCode: "AR",
        phoneCode: "+54",
        flag: "🇦🇷",
      },
      {
        country: "Armenia",
        isoCode: "AM",
        phoneCode: "+374",
        flag: "🇦🇲",
      },
      {
        country: "Aruba",
        isoCode: "AW",
        phoneCode: "+297",
        flag: "🇦🇼",
      },
      {
        country: "Australia",
        isoCode: "AU",
        phoneCode: "+61",
        flag: "🇦🇺",
      },
      {
        country: "Austria",
        isoCode: "AT",
        phoneCode: "+43",
        flag: "🇦🇹",
      },
      {
        country: "Azerbaijan",
        isoCode: "AZ",
        phoneCode: "+994",
        flag: "🇦🇿",
      },
      {
        country: "The Bahamas",
        isoCode: "BS",
        phoneCode: "++1-242",
        flag: "🇧🇸",
      },
      {
        country: "Bahrain",
        isoCode: "BH",
        phoneCode: "+973",
        flag: "🇧🇭",
      },
      {
        country: "Bangladesh",
        isoCode: "BD",
        phoneCode: "+880",
        flag: "🇧🇩",
      },
      {
        country: "Barbados",
        isoCode: "BB",
        phoneCode: "++1-246",
        flag: "🇧🇧",
      },
      {
        country: "Belarus",
        isoCode: "BY",
        phoneCode: "+375",
        flag: "🇧🇾",
      },
      {
        country: "Belgium",
        isoCode: "BE",
        phoneCode: "+32",
        flag: "🇧🇪",
      },
      {
        country: "Belize",
        isoCode: "BZ",
        phoneCode: "+501",
        flag: "🇧🇿",
      },
      {
        country: "Benin",
        isoCode: "BJ",
        phoneCode: "+229",
        flag: "🇧🇯",
      },
      {
        country: "Bermuda",
        isoCode: "BM",
        phoneCode: "++1-441",
        flag: "🇧🇲",
      },
      {
        country: "Bhutan",
        isoCode: "BT",
        phoneCode: "+975",
        flag: "🇧🇹",
      },
      {
        country: "Bolivia",
        isoCode: "BO",
        phoneCode: "+591",
        flag: "🇧🇴",
      },
      {
        country: "Bosnia and Herzegovina",
        isoCode: "BA",
        phoneCode: "+387",
        flag: "🇧🇦",
      },
      {
        country: "Botswana",
        isoCode: "BW",
        phoneCode: "+267",
        flag: "🇧🇼",
      },
      {
        country: "Bouvet Island",
        isoCode: "BV",
        phoneCode: "+0055",
        flag: "🇧🇻",
      },
      {
        country: "Brazil",
        isoCode: "BR",
        phoneCode: "+55",
        flag: "🇧🇷",
      },
      {
        country: "British Indian Ocean Territory",
        isoCode: "IO",
        phoneCode: "+246",
        flag: "🇮🇴",
      },
      {
        country: "Brunei",
        isoCode: "BN",
        phoneCode: "+673",
        flag: "🇧🇳",
      },
      {
        country: "Bulgaria",
        isoCode: "BG",
        phoneCode: "+359",
        flag: "🇧🇬",
      },
      {
        country: "Burkina Faso",
        isoCode: "BF",
        phoneCode: "+226",
        flag: "🇧🇫",
      },
      {
        country: "Burundi",
        isoCode: "BI",
        phoneCode: "+257",
        flag: "🇧🇮",
      },
      {
        country: "Cambodia",
        isoCode: "KH",
        phoneCode: "+855",
        flag: "🇰🇭",
      },
      {
        country: "Cameroon",
        isoCode: "CM",
        phoneCode: "+237",
        flag: "🇨🇲",
      },
      {
        country: "Canada",
        isoCode: "CA",
        phoneCode: "+1",
        flag: "🇨🇦",
      },
      {
        country: "Cape Verde",
        isoCode: "CV",
        phoneCode: "+238",
        flag: "🇨🇻",
      },
      {
        country: "Cayman Islands",
        isoCode: "KY",
        phoneCode: "++1-345",
        flag: "🇰🇾",
      },
      {
        country: "Central African Republic",
        isoCode: "CF",
        phoneCode: "+236",
        flag: "🇨🇫",
      },
      {
        country: "Chad",
        isoCode: "TD",
        phoneCode: "+235",
        flag: "🇹🇩",
      },
      {
        country: "Chile",
        isoCode: "CL",
        phoneCode: "+56",
        flag: "🇨🇱",
      },
      {
        country: "China",
        isoCode: "CN",
        phoneCode: "+86",
        flag: "🇨🇳",
      },
      {
        country: "Christmas Island",
        isoCode: "CX",
        phoneCode: "+61",
        flag: "🇨🇽",
      },
      {
        country: "Cocos (Keeling) Islands",
        isoCode: "CC",
        phoneCode: "+61",
        flag: "🇨🇨",
      },
      {
        country: "Colombia",
        isoCode: "CO",
        phoneCode: "+57",
        flag: "🇨🇴",
      },
      {
        country: "Comoros",
        isoCode: "KM",
        phoneCode: "+269",
        flag: "🇰🇲",
      },
      {
        country: "Congo",
        isoCode: "CG",
        phoneCode: "+242",
        flag: "🇨🇬",
      },
      {
        country: "Democratic Republic of the Congo",
        isoCode: "CD",
        phoneCode: "+243",
        flag: "🇨🇩",
      },
      {
        country: "Cook Islands",
        isoCode: "CK",
        phoneCode: "+682",
        flag: "🇨🇰",
      },
      {
        country: "Costa Rica",
        isoCode: "CR",
        phoneCode: "+506",
        flag: "🇨🇷",
      },
      {
        country: "Cote D'Ivoire (Ivory Coast)",
        isoCode: "CI",
        phoneCode: "+225",
        flag: "🇨🇮",
      },
      {
        country: "Croatia",
        isoCode: "HR",
        phoneCode: "+385",
        flag: "🇭🇷",
      },
      {
        country: "Cuba",
        isoCode: "CU",
        phoneCode: "+53",
        flag: "🇨🇺",
      },
      {
        country: "Cyprus",
        isoCode: "CY",
        phoneCode: "+357",
        flag: "🇨🇾",
      },
      {
        country: "Czech Republic",
        isoCode: "CZ",
        phoneCode: "+420",
        flag: "🇨🇿",
      },
      {
        country: "Denmark",
        isoCode: "DK",
        phoneCode: "+45",
        flag: "🇩🇰",
      },
      {
        country: "Djibouti",
        isoCode: "DJ",
        phoneCode: "+253",
        flag: "🇩🇯",
      },
      {
        country: "Dominica",
        isoCode: "DM",
        phoneCode: "++1-767",
        flag: "🇩🇲",
      },
      {
        country: "Dominican Republic",
        isoCode: "DO",
        phoneCode: "++1-809 and 1-829",
        flag: "🇩🇴",
      },
      {
        country: "East Timor",
        isoCode: "TL",
        phoneCode: "+670",
        flag: "🇹🇱",
      },
      {
        country: "Ecuador",
        isoCode: "EC",
        phoneCode: "+593",
        flag: "🇪🇨",
      },
      {
        country: "Egypt",
        isoCode: "EG",
        phoneCode: "+20",
        flag: "🇪🇬",
      },
      {
        country: "El Salvador",
        isoCode: "SV",
        phoneCode: "+503",
        flag: "🇸🇻",
      },
      {
        country: "Equatorial Guinea",
        isoCode: "GQ",
        phoneCode: "+240",
        flag: "🇬🇶",
      },
      {
        country: "Eritrea",
        isoCode: "ER",
        phoneCode: "+291",
        flag: "🇪🇷",
      },
      {
        country: "Estonia",
        isoCode: "EE",
        phoneCode: "+372",
        flag: "🇪🇪",
      },
      {
        country: "Ethiopia",
        isoCode: "ET",
        phoneCode: "+251",
        flag: "🇪🇹",
      },
      {
        country: "Falkland Islands",
        isoCode: "FK",
        phoneCode: "+500",
        flag: "🇫🇰",
      },
      {
        country: "Faroe Islands",
        isoCode: "FO",
        phoneCode: "+298",
        flag: "🇫🇴",
      },
      {
        country: "Fiji Islands",
        isoCode: "FJ",
        phoneCode: "+679",
        flag: "🇫🇯",
      },
      {
        country: "Finland",
        isoCode: "FI",
        phoneCode: "+358",
        flag: "🇫🇮",
      },
      {
        country: "France",
        isoCode: "FR",
        phoneCode: "+33",
        flag: "🇫🇷",
      },
      {
        country: "French Guiana",
        isoCode: "GF",
        phoneCode: "+594",
        flag: "🇬🇫",
      },
      {
        country: "French Polynesia",
        isoCode: "PF",
        phoneCode: "+689",
        flag: "🇵🇫",
      },
      {
        country: "French Southern Territories",
        isoCode: "TF",
        phoneCode: "+262",
        flag: "🇹🇫",
      },
      {
        country: "Gabon",
        isoCode: "GA",
        phoneCode: "+241",
        flag: "🇬🇦",
      },
      {
        country: "The Gambia",
        isoCode: "GM",
        phoneCode: "+220",
        flag: "🇬🇲",
      },
      {
        country: "Georgia",
        isoCode: "GE",
        phoneCode: "+995",
        flag: "🇬🇪",
      },
      {
        country: "Germany",
        isoCode: "DE",
        phoneCode: "+49",
        flag: "🇩🇪",
      },
      {
        country: "Ghana",
        isoCode: "GH",
        phoneCode: "+233",
        flag: "🇬🇭",
      },
      {
        country: "Gibraltar",
        isoCode: "GI",
        phoneCode: "+350",
        flag: "🇬🇮",
      },
      {
        country: "Greece",
        isoCode: "GR",
        phoneCode: "+30",
        flag: "🇬🇷",
      },
      {
        country: "Greenland",
        isoCode: "GL",
        phoneCode: "+299",
        flag: "🇬🇱",
      },
      {
        country: "Grenada",
        isoCode: "GD",
        phoneCode: "++1-473",
        flag: "🇬🇩",
      },
      {
        country: "Guadeloupe",
        isoCode: "GP",
        phoneCode: "+590",
        flag: "🇬🇵",
      },
      {
        country: "Guam",
        isoCode: "GU",
        phoneCode: "++1-671",
        flag: "🇬🇺",
      },
      {
        country: "Guatemala",
        isoCode: "GT",
        phoneCode: "+502",
        flag: "🇬🇹",
      },
      {
        country: "Guernsey and Alderney",
        isoCode: "GG",
        phoneCode: "++44-1481",
        flag: "🇬🇬",
      },
      {
        country: "Guinea",
        isoCode: "GN",
        phoneCode: "+224",
        flag: "🇬🇳",
      },
      {
        country: "Guinea-Bissau",
        isoCode: "GW",
        phoneCode: "+245",
        flag: "🇬🇼",
      },
      {
        country: "Guyana",
        isoCode: "GY",
        phoneCode: "+592",
        flag: "🇬🇾",
      },
      {
        country: "Haiti",
        isoCode: "HT",
        phoneCode: "+509",
        flag: "🇭🇹",
      },
      {
        country: "Heard Island and McDonald Islands",
        isoCode: "HM",
        phoneCode: "+672",
        flag: "🇭🇲",
      },
      {
        country: "Honduras",
        isoCode: "HN",
        phoneCode: "+504",
        flag: "🇭🇳",
      },
      {
        country: "Hong Kong S.A.R.",
        isoCode: "HK",
        phoneCode: "+852",
        flag: "🇭🇰",
      },
      {
        country: "Hungary",
        isoCode: "HU",
        phoneCode: "+36",
        flag: "🇭🇺",
      },
      {
        country: "Iceland",
        isoCode: "IS",
        phoneCode: "+354",
        flag: "🇮🇸",
      },
      {
        country: "India",
        isoCode: "IN",
        phoneCode: "+91",
        flag: "🇮🇳",
      },
      {
        country: "Indonesia",
        isoCode: "ID",
        phoneCode: "+62",
        flag: "🇮🇩",
      },
      {
        country: "Iran",
        isoCode: "IR",
        phoneCode: "+98",
        flag: "🇮🇷",
      },
      {
        country: "Iraq",
        isoCode: "IQ",
        phoneCode: "+964",
        flag: "🇮🇶",
      },
      {
        country: "Ireland",
        isoCode: "IE",
        phoneCode: "+353",
        flag: "🇮🇪",
      },
      {
        country: "Israel",
        isoCode: "IL",
        phoneCode: "+972",
        flag: "🇮🇱",
      },
      {
        country: "Italy",
        isoCode: "IT",
        phoneCode: "+39",
        flag: "🇮🇹",
      },
      {
        country: "Jamaica",
        isoCode: "JM",
        phoneCode: "++1-876",
        flag: "🇯🇲",
      },
      {
        country: "Japan",
        isoCode: "JP",
        phoneCode: "+81",
        flag: "🇯🇵",
      },
      {
        country: "Jersey",
        isoCode: "JE",
        phoneCode: "++44-1534",
        flag: "🇯🇪",
      },
      {
        country: "Jordan",
        isoCode: "JO",
        phoneCode: "+962",
        flag: "🇯🇴",
      },
      {
        country: "Kazakhstan",
        isoCode: "KZ",
        phoneCode: "+7",
        flag: "🇰🇿",
      },
      {
        country: "Kenya",
        isoCode: "KE",
        phoneCode: "+254",
        flag: "🇰🇪",
      },
      {
        country: "Kiribati",
        isoCode: "KI",
        phoneCode: "+686",
        flag: "🇰🇮",
      },
      {
        country: "North Korea",
        isoCode: "KP",
        phoneCode: "+850",
        flag: "🇰🇵",
      },
      {
        country: "South Korea",
        isoCode: "KR",
        phoneCode: "+82",
        flag: "🇰🇷",
      },
      {
        country: "Kuwait",
        isoCode: "KW",
        phoneCode: "+965",
        flag: "🇰🇼",
      },
      {
        country: "Kyrgyzstan",
        isoCode: "KG",
        phoneCode: "+996",
        flag: "🇰🇬",
      },
      {
        country: "Laos",
        isoCode: "LA",
        phoneCode: "+856",
        flag: "🇱🇦",
      },
      {
        country: "Latvia",
        isoCode: "LV",
        phoneCode: "+371",
        flag: "🇱🇻",
      },
      {
        country: "Lebanon",
        isoCode: "LB",
        phoneCode: "+961",
        flag: "🇱🇧",
      },
      {
        country: "Lesotho",
        isoCode: "LS",
        phoneCode: "+266",
        flag: "🇱🇸",
      },
      {
        country: "Liberia",
        isoCode: "LR",
        phoneCode: "+231",
        flag: "🇱🇷",
      },
      {
        country: "Libya",
        isoCode: "LY",
        phoneCode: "+218",
        flag: "🇱🇾",
      },
      {
        country: "Liechtenstein",
        isoCode: "LI",
        phoneCode: "+423",
        flag: "🇱🇮",
      },
      {
        country: "Lithuania",
        isoCode: "LT",
        phoneCode: "+370",
        flag: "🇱🇹",
      },
      {
        country: "Luxembourg",
        isoCode: "LU",
        phoneCode: "+352",
        flag: "🇱🇺",
      },
      {
        country: "Macau S.A.R.",
        isoCode: "MO",
        phoneCode: "+853",
        flag: "🇲🇴",
      },
      {
        country: "Macedonia",
        isoCode: "MK",
        phoneCode: "+389",
        flag: "🇲🇰",
      },
      {
        country: "Madagascar",
        isoCode: "MG",
        phoneCode: "+261",
        flag: "🇲🇬",
      },
      {
        country: "Malawi",
        isoCode: "MW",
        phoneCode: "+265",
        flag: "🇲🇼",
      },
      {
        country: "Malaysia",
        isoCode: "MY",
        phoneCode: "+60",
        flag: "🇲🇾",
      },
      {
        country: "Maldives",
        isoCode: "MV",
        phoneCode: "+960",
        flag: "🇲🇻",
      },
      {
        country: "Mali",
        isoCode: "ML",
        phoneCode: "+223",
        flag: "🇲🇱",
      },
      {
        country: "Malta",
        isoCode: "MT",
        phoneCode: "+356",
        flag: "🇲🇹",
      },
      {
        country: "Man (Isle of)",
        isoCode: "IM",
        phoneCode: "++44-1624",
        flag: "🇮🇲",
      },
      {
        country: "Marshall Islands",
        isoCode: "MH",
        phoneCode: "+692",
        flag: "🇲🇭",
      },
      {
        country: "Martinique",
        isoCode: "MQ",
        phoneCode: "+596",
        flag: "🇲🇶",
      },
      {
        country: "Mauritania",
        isoCode: "MR",
        phoneCode: "+222",
        flag: "🇲🇷",
      },
      {
        country: "Mauritius",
        isoCode: "MU",
        phoneCode: "+230",
        flag: "🇲🇺",
      },
      {
        country: "Mayotte",
        isoCode: "YT",
        phoneCode: "+262",
        flag: "🇾🇹",
      },
      {
        country: "Mexico",
        isoCode: "MX",
        phoneCode: "+52",
        flag: "🇲🇽",
      },
      {
        country: "Micronesia",
        isoCode: "FM",
        phoneCode: "+691",
        flag: "🇫🇲",
      },
      {
        country: "Moldova",
        isoCode: "MD",
        phoneCode: "+373",
        flag: "🇲🇩",
      },
      {
        country: "Monaco",
        isoCode: "MC",
        phoneCode: "+377",
        flag: "🇲🇨",
      },
      {
        country: "Mongolia",
        isoCode: "MN",
        phoneCode: "+976",
        flag: "🇲🇳",
      },
      {
        country: "Montenegro",
        isoCode: "ME",
        phoneCode: "+382",
        flag: "🇲🇪",
      },
      {
        country: "Montserrat",
        isoCode: "MS",
        phoneCode: "++1-664",
        flag: "🇲🇸",
      },
      {
        country: "Morocco",
        isoCode: "MA",
        phoneCode: "+212",
        flag: "🇲🇦",
      },
      {
        country: "Mozambique",
        isoCode: "MZ",
        phoneCode: "+258",
        flag: "🇲🇿",
      },
      {
        country: "Myanmar",
        isoCode: "MM",
        phoneCode: "+95",
        flag: "🇲🇲",
      },
      {
        country: "Namibia",
        isoCode: "NA",
        phoneCode: "+264",
        flag: "🇳🇦",
      },
      {
        country: "Nauru",
        isoCode: "NR",
        phoneCode: "+674",
        flag: "🇳🇷",
      },
      {
        country: "Nepal",
        isoCode: "NP",
        phoneCode: "+977",
        flag: "🇳🇵",
      },
      {
        country: "Bonaire, Sint Eustatius and Saba",
        isoCode: "BQ",
        phoneCode: "+599",
        flag: "🇧🇶",
      },
      {
        country: "Netherlands",
        isoCode: "NL",
        phoneCode: "+31",
        flag: "🇳🇱",
      },
      {
        country: "New Caledonia",
        isoCode: "NC",
        phoneCode: "+687",
        flag: "🇳🇨",
      },
      {
        country: "New Zealand",
        isoCode: "NZ",
        phoneCode: "+64",
        flag: "🇳🇿",
      },
      {
        country: "Nicaragua",
        isoCode: "NI",
        phoneCode: "+505",
        flag: "🇳🇮",
      },
      {
        country: "Niger",
        isoCode: "NE",
        phoneCode: "+227",
        flag: "🇳🇪",
      },
      {
        country: "Nigeria",
        isoCode: "NG",
        phoneCode: "+234",
        flag: "🇳🇬",
      },
      {
        country: "Niue",
        isoCode: "NU",
        phoneCode: "+683",
        flag: "🇳🇺",
      },
      {
        country: "Norfolk Island",
        isoCode: "NF",
        phoneCode: "+672",
        flag: "🇳🇫",
      },
      {
        country: "Northern Mariana Islands",
        isoCode: "MP",
        phoneCode: "++1-670",
        flag: "🇲🇵",
      },
      {
        country: "Norway",
        isoCode: "NO",
        phoneCode: "+47",
        flag: "🇳🇴",
      },
      {
        country: "Oman",
        isoCode: "OM",
        phoneCode: "+968",
        flag: "🇴🇲",
      },
      {
        country: "Pakistan",
        isoCode: "PK",
        phoneCode: "+92",
        flag: "🇵🇰",
      },
      {
        country: "Palau",
        isoCode: "PW",
        phoneCode: "+680",
        flag: "🇵🇼",
      },
      {
        country: "Palestinian Territory Occupied",
        isoCode: "PS",
        phoneCode: "+970",
        flag: "🇵🇸",
      },
      {
        country: "Panama",
        isoCode: "PA",
        phoneCode: "+507",
        flag: "🇵🇦",
      },
      {
        country: "Papua new Guinea",
        isoCode: "PG",
        phoneCode: "+675",
        flag: "🇵🇬",
      },
      {
        country: "Paraguay",
        isoCode: "PY",
        phoneCode: "+595",
        flag: "🇵🇾",
      },
      {
        country: "Peru",
        isoCode: "PE",
        phoneCode: "+51",
        flag: "🇵🇪",
      },
      {
        country: "Philippines",
        isoCode: "PH",
        phoneCode: "+63",
        flag: "🇵🇭",
      },
      {
        country: "Pitcairn Island",
        isoCode: "PN",
        phoneCode: "+870",
        flag: "🇵🇳",
      },
      {
        country: "Poland",
        isoCode: "PL",
        phoneCode: "+48",
        flag: "🇵🇱",
      },
      {
        country: "Portugal",
        isoCode: "PT",
        phoneCode: "+351",
        flag: "🇵🇹",
      },
      {
        country: "Puerto Rico",
        isoCode: "PR",
        phoneCode: "++1-787 and 1-939",
        flag: "🇵🇷",
      },
      {
        country: "Qatar",
        isoCode: "QA",
        phoneCode: "+974",
        flag: "🇶🇦",
      },
      {
        country: "Reunion",
        isoCode: "RE",
        phoneCode: "+262",
        flag: "🇷🇪",
      },
      {
        country: "Romania",
        isoCode: "RO",
        phoneCode: "+40",
        flag: "🇷🇴",
      },
      {
        country: "Russia",
        isoCode: "RU",
        phoneCode: "+7",
        flag: "🇷🇺",
      },
      {
        country: "Rwanda",
        isoCode: "RW",
        phoneCode: "+250",
        flag: "🇷🇼",
      },
      {
        country: "Saint Helena",
        isoCode: "SH",
        phoneCode: "+290",
        flag: "🇸🇭",
      },
      {
        country: "Saint Kitts And Nevis",
        isoCode: "KN",
        phoneCode: "++1-869",
        flag: "🇰🇳",
      },
      {
        country: "Saint Lucia",
        isoCode: "LC",
        phoneCode: "++1-758",
        flag: "🇱🇨",
      },
      {
        country: "Saint Pierre and Miquelon",
        isoCode: "PM",
        phoneCode: "+508",
        flag: "🇵🇲",
      },
      {
        country: "Saint Vincent And The Grenadines",
        isoCode: "VC",
        phoneCode: "++1-784",
        flag: "🇻🇨",
      },
      {
        country: "Saint-Barthelemy",
        isoCode: "BL",
        phoneCode: "+590",
        flag: "🇧🇱",
      },
      {
        country: "Saint-Martin (French part)",
        isoCode: "MF",
        phoneCode: "+590",
        flag: "🇲🇫",
      },
      {
        country: "Samoa",
        isoCode: "WS",
        phoneCode: "+685",
        flag: "🇼🇸",
      },
      {
        country: "San Marino",
        isoCode: "SM",
        phoneCode: "+378",
        flag: "🇸🇲",
      },
      {
        country: "Sao Tome and Principe",
        isoCode: "ST",
        phoneCode: "+239",
        flag: "🇸🇹",
      },
      {
        country: "Saudi Arabia",
        isoCode: "SA",
        phoneCode: "+966",
        flag: "🇸🇦",
      },
      {
        country: "Senegal",
        isoCode: "SN",
        phoneCode: "+221",
        flag: "🇸🇳",
      },
      {
        country: "Serbia",
        isoCode: "RS",
        phoneCode: "+381",
        flag: "🇷🇸",
      },
      {
        country: "Seychelles",
        isoCode: "SC",
        phoneCode: "+248",
        flag: "🇸🇨",
      },
      {
        country: "Sierra Leone",
        isoCode: "SL",
        phoneCode: "+232",
        flag: "🇸🇱",
      },
      {
        country: "Singapore",
        isoCode: "SG",
        phoneCode: "+65",
        flag: "🇸🇬",
      },
      {
        country: "Slovakia",
        isoCode: "SK",
        phoneCode: "+421",
        flag: "🇸🇰",
      },
      {
        country: "Slovenia",
        isoCode: "SI",
        phoneCode: "+386",
        flag: "🇸🇮",
      },
      {
        country: "Solomon Islands",
        isoCode: "SB",
        phoneCode: "+677",
        flag: "🇸🇧",
      },
      {
        country: "Somalia",
        isoCode: "SO",
        phoneCode: "+252",
        flag: "🇸🇴",
      },
      {
        country: "South Africa",
        isoCode: "ZA",
        phoneCode: "+27",
        flag: "🇿🇦",
      },
      {
        country: "South Georgia",
        isoCode: "GS",
        phoneCode: "+500",
        flag: "🇬🇸",
      },
      {
        country: "South Sudan",
        isoCode: "SS",
        phoneCode: "+211",
        flag: "🇸🇸",
      },
      {
        country: "Spain",
        isoCode: "ES",
        phoneCode: "+34",
        flag: "🇪🇸",
      },
      {
        country: "Sri Lanka",
        isoCode: "LK",
        phoneCode: "+94",
        flag: "🇱🇰",
      },
      {
        country: "Sudan",
        isoCode: "SD",
        phoneCode: "+249",
        flag: "🇸🇩",
      },
      {
        country: "Suriname",
        isoCode: "SR",
        phoneCode: "+597",
        flag: "🇸🇷",
      },
      {
        country: "Svalbard And Jan Mayen Islands",
        isoCode: "SJ",
        phoneCode: "+47",
        flag: "🇸🇯",
      },
      {
        country: "Swaziland",
        isoCode: "SZ",
        phoneCode: "+268",
        flag: "🇸🇿",
      },
      {
        country: "Sweden",
        isoCode: "SE",
        phoneCode: "+46",
        flag: "🇸🇪",
      },
      {
        country: "Switzerland",
        isoCode: "CH",
        phoneCode: "+41",
        flag: "🇨🇭",
      },
      {
        country: "Syria",
        isoCode: "SY",
        phoneCode: "+963",
        flag: "🇸🇾",
      },
      {
        country: "Taiwan",
        isoCode: "TW",
        phoneCode: "+886",
        flag: "🇹🇼",
      },
      {
        country: "Tajikistan",
        isoCode: "TJ",
        phoneCode: "+992",
        flag: "🇹🇯",
      },
      {
        country: "Tanzania",
        isoCode: "TZ",
        phoneCode: "+255",
        flag: "🇹🇿",
      },
      {
        country: "Thailand",
        isoCode: "TH",
        phoneCode: "+66",
        flag: "🇹🇭",
      },
      {
        country: "Togo",
        isoCode: "TG",
        phoneCode: "+228",
        flag: "🇹🇬",
      },
      {
        country: "Tokelau",
        isoCode: "TK",
        phoneCode: "+690",
        flag: "🇹🇰",
      },
      {
        country: "Tonga",
        isoCode: "TO",
        phoneCode: "+676",
        flag: "🇹🇴",
      },
      {
        country: "Trinidad And Tobago",
        isoCode: "TT",
        phoneCode: "++1-868",
        flag: "🇹🇹",
      },
      {
        country: "Tunisia",
        isoCode: "TN",
        phoneCode: "+216",
        flag: "🇹🇳",
      },
      {
        country: "Turkey",
        isoCode: "TR",
        phoneCode: "+90",
        flag: "🇹🇷",
      },
      {
        country: "Turkmenistan",
        isoCode: "TM",
        phoneCode: "+993",
        flag: "🇹🇲",
      },
      {
        country: "Turks And Caicos Islands",
        isoCode: "TC",
        phoneCode: "++1-649",
        flag: "🇹🇨",
      },
      {
        country: "Tuvalu",
        isoCode: "TV",
        phoneCode: "+688",
        flag: "🇹🇻",
      },
      {
        country: "Uganda",
        isoCode: "UG",
        phoneCode: "+256",
        flag: "🇺🇬",
      },
      {
        country: "Ukraine",
        isoCode: "UA",
        phoneCode: "+380",
        flag: "🇺🇦",
      },
      {
        country: "United Arab Emirates",
        isoCode: "AE",
        phoneCode: "+971",
        flag: "🇦🇪",
      },
      {
        country: "United Kingdom",
        isoCode: "GB",
        phoneCode: "+44",
        flag: "🇬🇧",
      },
      {
        country: "United States",
        isoCode: "US",
        phoneCode: "+1",
        flag: "🇺🇸",
      },
      {
        country: "United States Minor Outlying Islands",
        isoCode: "UM",
        phoneCode: "+1",
        flag: "🇺🇲",
      },
      {
        country: "Uruguay",
        isoCode: "UY",
        phoneCode: "+598",
        flag: "🇺🇾",
      },
      {
        country: "Uzbekistan",
        isoCode: "UZ",
        phoneCode: "+998",
        flag: "🇺🇿",
      },
      {
        country: "Vanuatu",
        isoCode: "VU",
        phoneCode: "+678",
        flag: "🇻🇺",
      },
      {
        country: "Vatican City State (Holy See)",
        isoCode: "VA",
        phoneCode: "+379",
        flag: "🇻🇦",
      },
      {
        country: "Venezuela",
        isoCode: "VE",
        phoneCode: "+58",
        flag: "🇻🇪",
      },
      {
        country: "Vietnam",
        isoCode: "VN",
        phoneCode: "+84",
        flag: "🇻🇳",
      },
      {
        country: "Virgin Islands (British)",
        isoCode: "VG",
        phoneCode: "++1-284",
        flag: "🇻🇬",
      },
      {
        country: "Virgin Islands (US)",
        isoCode: "VI",
        phoneCode: "++1-340",
        flag: "🇻🇮",
      },
      {
        country: "Wallis And Futuna Islands",
        isoCode: "WF",
        phoneCode: "+681",
        flag: "🇼🇫",
      },
      {
        country: "Western Sahara",
        isoCode: "EH",
        phoneCode: "+212",
        flag: "🇪🇭",
      },
      {
        country: "Yemen",
        isoCode: "YE",
        phoneCode: "+967",
        flag: "🇾🇪",
      },
      {
        country: "Zambia",
        isoCode: "ZM",
        phoneCode: "+260",
        flag: "🇿🇲",
      },
      {
        country: "Zimbabwe",
        isoCode: "ZW",
        phoneCode: "+263",
        flag: "🇿🇼",
      },
      {
        country: "Kosovo",
        isoCode: "XK",
        phoneCode: "+383",
        flag: "🇽🇰",
      },
      {
        country: "Curaçao",
        isoCode: "CW",
        phoneCode: "+599",
        flag: "🇨🇼",
      },
      {
        country: "Sint Maarten (Dutch part)",
        isoCode: "SX",
        phoneCode: "+1721",
        flag: "🇸🇽",
      },
    ],
  },
  message: "Mobile codes fetched successfully",
  success: true,
};
