export const ApiRoutes = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL,
  USER_LOGIN: "/auth/login",
  USER_LOGOUT: "/auth/logout",
  REFRESH: "/auth/refresh",
  FORGOT_PASSWORD: "/auth/forgotPassword",
  RESET_PASSWORD: "/auth/resetPassword",
  ATTACHMENTS: "/attachments",
  ATTACHMENTS_SPECIFIC: "/attachments/:id",
  PROSPECTS: "/prospects",
  GET_PROSPECT: "/prospects/:id",
  CONVERT_TO_MEMBER: "/prospects/:id/convertToMember",

  GET_ACTIVITY_TYPES: "/clubs/:id/activityTypes",
  GET_MEMBERSHIP_CATEGORIES: "/clubs/:id/membershipCategories",
  GET_LEAD_SOURCES: "/clubs/:id/leadSources",
  GET_LEAD_STATUSES: "/clubs/:id/leadStatuses",
  GET_EMAIL_TEMPLATES: "/clubs/:id/emailTemplates",
  Add_ACTIVITY: "/prospects/:id/activity",

  MEMBERSHIP_STATUS: "settings/:id/membershipStatuses",
  MEMBERSHIP_TYPE_STATUS: "settings/:id/membershipCategories",
  MEMBERS: "members",
  STAFF_MEMBER_DETAILS: "/staffs/:id",
  MEMBER_DETAILS: "/members/:id",
  SEND_EMAIL: "/email",
};
